// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Device struct {
	ID        string
	Name      string
	Brand     string
	State     string
	CreatedAt time.Time
}
