// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO devices (id, name, brand, state, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDeviceParams struct {
	ID        string
	Name      string
	Brand     string
	State     string
	CreatedAt time.Time
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.Brand,
		arg.State,
		arg.CreatedAt,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getAllDevices = `-- name: GetAllDevices :many
SELECT id, name, brand, state, created_at FROM devices
`

func (q *Queries) GetAllDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDevicesByBrand = `-- name: GetAllDevicesByBrand :many
SELECT id, name, brand, state, created_at FROM devices 
WHERE brand = $1
`

func (q *Queries) GetAllDevicesByBrand(ctx context.Context, brand string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevicesByBrand, brand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDevicesByState = `-- name: GetAllDevicesByState :many
SELECT id, name, brand, state, created_at FROM devices 
WHERE state = $1
`

func (q *Queries) GetAllDevicesByState(ctx context.Context, state string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, getAllDevicesByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Brand,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, name, brand, state, created_at FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Brand,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :exec
UPDATE devices
SET name = $1,
    brand = $2,
    state = $3
WHERE id = $4
`

type UpdateDeviceParams struct {
	Name  string
	Brand string
	State string
	ID    string
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, updateDevice,
		arg.Name,
		arg.Brand,
		arg.State,
		arg.ID,
	)
	return err
}
